---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant
  handlers:
  - name: reload apache
    service: name=apache2 state=reloaded
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - include: tasks/apache.yaml
    - include: tasks/mysql.yaml
    - include: tasks/php.yaml
  handlers:
  - name: reload apache
    service: name=apache2 state=reloaded
